1. Import numpy and pandas libraries in the notebook
2. load automobile.csv file in the notebook
3. Do a basic inspection and print the first and last 15 rows of your dataframe
4. You need to clean the data a little bit now. Replace all column values with the values ? and n.a with NaN
5. Print the company name which manufactured the most expensive car. Also print the price of the most expensive car
6. Calculate Maximum Horsepower for Each Company
7. Print the total number of cars manufactured by each company
8. Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled
9.

In [122]:
import numpy as np
import pandas as pd

In [123]:
cars = pd.read_csv("Automobile_data.csv")
cars

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [124]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [125]:
cars.isnull().sum() # To check whether the dataset has null values or not

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [126]:
cars.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [127]:
cars.shape

(205, 26)

In [128]:
cars.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565

In [129]:
cars.tail(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.5,90,5500,24,29,9980
191,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.4,8.5,110,5500,19,24,13295
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.4,23.0,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.4,9.0,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [130]:
list_of = list(cars.columns)
for i in list_of:
  cars[i] = cars[i].replace('?',np.nan)
  print(cars[i])

0      3
1      3
2      1
3      2
4      2
      ..
200   -1
201   -1
202   -1
203   -1
204   -1
Name: symboling, Length: 205, dtype: int64
0      NaN
1      NaN
2      NaN
3      164
4      164
      ...
200     95
201     95
202     95
203     95
204     95
Name: normalized-losses, Length: 205, dtype: object
0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object
0         gas
1         gas
2         gas
3         gas
4         gas
        ...
200       gas
201       gas
202       gas
203    diesel
204       gas
Name: fuel-type, Length: 205, dtype: object
0        std
1        std
2        std
3        std
4        std
       ...
200      std
201    turbo
202      std
203    turbo
204    turbo
Name: aspiration, Length: 205, dtype: object
0       two
1       two
2       two
3      four
4      four
       ...
200    four
201    four
202    four
203    four
204    four
Name: num-of-doors, Length: 205, dtype: object
0      convertible
1      convertible
2        hatchback
3            sedan
4            sedan
          ...
200          sedan
201          sedan
202          sedan
203          sedan
204          sedan
Name: body-style, Length: 205, dtype: object
0      rwd
1      rwd
2      rwd
3      fwd
4      4wd
      ...
200    rwd
201    rwd
202    rwd
203    rwd
204    rwd
Name: drive-wheels, Length: 205, dtype: object
0      front
1      front
2      front
3      front
4      front
       ...
200    front
201    front
202    front
203    front
204    front
Name: engine-location, Length: 205, dtype: object
0       88.6
1       88.6
2       94.5
3       99.8
4       99.4
       ...
200    109.1
201    109.1
202    109.1
203    109.1
204    109.1
Name: wheel-base, Length: 205, dtype: float64
0      168.8
1      168.8
2      171.2
3      176.6
4      176.6
       ...
200    188.8
201    188.8
202    188.8
203    188.8
204    188.8
Name: length, Length: 205, dtype: float64
0      64.1
1      64.1
2      65.5
3      66.2
4      66.4
       ...
200    68.9
201    68.8
202    68.9
203    68.9
204    68.9
Name: width, Length: 205, dtype: float64
0      48.8
1      48.8
2      52.4
3      54.3
4      54.3
       ...
200    55.5
201    55.5
202    55.5
203    55.5
204    55.5
Name: height, Length: 205, dtype: float64
0      2548
1      2548
2      2823
3      2337
4      2824
       ...
200    2952
201    3049
202    3012
203    3217
204    3062
Name: curb-weight, Length: 205, dtype: int64
0      dohc
1      dohc
2      ohcv
3       ohc
4       ohc
       ...
200     ohc
201     ohc
202    ohcv
203     ohc
204     ohc
Name: engine-type, Length: 205, dtype: object
0      four
1      four
2       six
3      four
4      five
       ...
200    four
201    four
202     six
203     six
204    four
Name: num-of-cylinders, Length: 205, dtype: object
0      130
1      130
2      152
3      109
4      136
      ...
200    141
201    141
202    173
203    145
204    141
Name: engine-size, Length: 205, dtype: int64
0      mpfi
1      mpfi
2      mpfi
3      mpfi
4      mpfi
       ...
200    mpfi
201    mpfi
202    mpfi
203     idi
204    mpfi
Name: fuel-system, Length: 205, dtype: object
0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ...
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: object
0      2.68
1      2.68
2      3.47
3       3.4
4       3.4
       ...
200    3.15
201    3.15
202    2.87
203     3.4
204    3.15
Name: stroke, Length: 205, dtype: object
0       9.0
1       9.0
2       9.0
3      10.0
4       8.0
       ...
200     9.5
201     8.7
202     8.8
203    23.0
204     9.5
Name: compression-ratio, Length: 205, dtype: float64
0      111
1      111
2      154
3      102
4      115
      ...
200    114
201    160
202    134
203    106
204    114
Name: horsepower, Length: 205, dtype: object
0      5000
1      5000
2      5000
3      5500
4      5500
       ...
200    5400
201    5300
202    5500
203    4800
204    5400
Name: peak-rpm, Length: 205, dtype: object
0      21
1      21
2      19
3      24
4      18
       ..
200    23
201    19
202    18
203    26
204    19
Name: city-mpg, Length: 205, dtype: int64
0      27
1      27
2      26
3      30
4      22
       ..
200    28
201    25
202    23
203    27
204    25
Name: highway-mpg, Length: 205, dtype: int64
0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: object

In [131]:
cars['price'] = pd.to_numeric(cars['price'], errors='coerce')

In [132]:
cars['price'].max()

45400.0

In [133]:
cars.groupby(['make'])['horsepower'].max().reset_index()

             make horsepower
0     alfa-romero        154
1            audi        160
2             bmw        182
3       chevrolet         70
4           dodge         88
5           honda         86
6           isuzu         90
7          jaguar        262
8           mazda         84
9   mercedes-benz        184
10        mercury        175
11     mitsubishi         88
12         nissan         97
13         peugot         97
14       plymouth         88
15        porsche        288
16        renault        NaN
17           saab        160
18         subaru         94
19         toyota         92
20     volkswagen         90
21          volvo        162

In [134]:
cars.groupby(['make'])['make'].count()

make
alfa-romero       3
audi              7
bmw               8
chevrolet         3
dodge             9
honda            13
isuzu             4
jaguar            3
mazda            17
mercedes-benz     8
mercury           1
mitsubishi       13
nissan           18
peugot           11
plymouth          7
porsche           5
renault           2
saab              6
subaru           12
toyota           32
volkswagen       12
volvo            11
Name: make, dtype: int64

In [135]:
def UPD(engine, price):
    if engine=='rear': updated_price = price * 2
    else: updated_price = price
    return updated_price

In [136]:
cars['updated_price'] = cars.apply(lambda x: UPD_PRC(x['engine-location'],x['price']),axis=1)
cars

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,front
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,front
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,front
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0,front
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0,front
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,front
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,front
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,front
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.4,23.0,106,4800,26,27,22470.0,front
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,front

In [137]:
cars.sort_values(['make','price'],ascending = [True,True]).head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,front
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,front
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,front
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102,5500,24,30,13950.0,front
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,8.5,110,5500,19,25,15250.0,front
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115,5500,18,22,17450.0,front
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,mpfi,3.19,3.4,8.5,110,5500,19,25,17710.0,front
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,mpfi,3.19,3.4,8.5,110,5500,19,25,18920.0,front
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,mpfi,3.13,3.4,8.3,140,5500,17,20,23875.0,front
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,mpfi,3.13,3.4,7.0,160,5500,16,22,NaN,front
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,mpfi,3.5,2.8,8.8,101,5800,23,29,16430.0,front
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,mpfi,3.5,2.8,8.8,101,5800,23,29,16925.0,front
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.0,front
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,mpfi,3.31,3.19,9.0,121,4250,21,28,21105.0,front
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.0,front

In [138]:
int_doors = 0
def INT_DOORS(doors):
    if doors == 'two':int_doors =+ 2
    elif doors == 'four':int_doors =+ 4
    else: return None
    return int_doors

In [140]:
cars['int-doors'] = cars.apply(lambda x: INT_DOORS(x['num-of-doors']),axis = 1)
cars.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,updated_price,int-doors
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495.0,front,2.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500.0,front,2.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,front,2.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.4,10.0,102,5500,24,30,13950.0,front,4.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.4,8.0,115,5500,18,22,17450.0,front,4.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.19,3.4,8.5,110,5500,19,25,15250.0,front,2.0
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,3.19,3.4,8.5,110,5500,19,25,17710.0,front,4.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,3.19,3.4,8.5,110,5500,19,25,18920.0,front,4.0
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,3.13,3.4,8.3,140,5500,17,20,23875.0,front,4.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,3.13,3.4,7.0,160,5500,16,22,NaN,front,2.0
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,3.5,2.8,8.8,101,5800,23,29,16430.0,front,2.0
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,3.5,2.8,8.8,101,5800,23,29,16925.0,front,4.0
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,3.31,3.19,9.0,121,4250,21,28,20970.0,front,2.0
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,3.31,3.19,9.0,121,4250,21,28,21105.0,front,4.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,3.31,3.19,9.0,121,4250,20,25,24565.0,front,4.0

In [144]:
cars1 = pd.DataFrame({'Company':['Ford','Mercedes','BMW','Audi'],'Price':[30000,450000,134560,75000]}, index=[0,1,2,3])
cars2 = pd.DataFrame({'Company':['Maruti Suzuki','Honda','Toyota','Tata'],'Price':[400000,450000,600000,750000]}, index=[4,5,6,7])
pd.concat([cars1,cars2])

         Company   Price
0           Ford   30000
1       Mercedes  450000
2            BMW  134560
3           Audi   75000
4  Maruti Suzuki  400000
5          Honda  450000
6         Toyota  600000
7           Tata  750000

In [145]:
pd.concat([cars1,cars2],axis = 1)

    Company     Price        Company     Price
0      Ford   30000.0            NaN       NaN
1  Mercedes  450000.0            NaN       NaN
2       BMW  134560.0            NaN       NaN
3      Audi   75000.0            NaN       NaN
4       NaN       NaN  Maruti Suzuki  400000.0
5       NaN       NaN          Honda  450000.0
6       NaN       NaN         Toyota  600000.0
7       NaN       NaN           Tata  750000.0